AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:

  Function:
    FunctionUrlConfig:
      AuthType: NONE
    Timeout: 30
    Runtime: java11
    MemorySize: 1024

Resources:

  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: serverless2049-lambda-function-MainFunction
      CodeUri: ./main-function
      Handler: com.lineup.function.main.Function
      Environment:
        Variables:
          DYNAMO_DB_TABLE_NAME: serverless2049-dynamodb-table-Database
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: serverless2049-lambda-function-TestFunction
      CodeUri: ./test-function
      Handler: com.lineup.function.test.Function
      Environment:
        Variables:
          MAIN_FUNCTION_URL: !GetAtt MainFunctionUrl.FunctionUrl
      Policies:
        - CloudWatchLogsFullAccess

  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: serverless2049-dynamodb-table-Database
      PrimaryKey:
        Name: id
        Type: String
